# Generated by Django 2.2.5 on 2019-09-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200, verbose_name='Conteúdo')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em:')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200, verbose_name='Conteúdo')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em:')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfis.Perfil')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacoes.Tweet')),
            ],
        ),
    ]
