# Generated by Django 2.2.5 on 2019-09-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20190913_1141'),
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(related_name='tweets_liked', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='perfis.Perfil'),
        ),
    ]
