# Generated by Django 2.2.5 on 2019-09-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_auto_20190913_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicacoes.Tweet'),
        ),
    ]
